import {NativeModules} from 'react-native';
import {getStoredPrimaryColor} from '../../utils/primaryColorStorage';
import {DEFAULT_PRIMARY_COLOR_ID, findPrimaryColorOption} from '../../theme/personalizationPalette';

const {PickerTheme} = NativeModules;

/**
 * Applies the currently active primary-color accent to the host Activity's
 * theme (Android only — no-op elsewhere) so a native picker opened right
 * after this resolves matches the app's actual color instead of a static
 * default. Android themes only resolve compiled resources, so this can only
 * pick from the finite palette generated by
 * scripts/generateAndroidThemeColors.js into
 * android/app/src/main/res/values/theme_styles_generated.xml. Never throws —
 * a cosmetic touch-up, not worth blocking the picker from opening over.
 */
export const applyPickerAccentForCurrentColor = async (): Promise<void> => {
  if (!PickerTheme?.applyAccentStyle) return;
  try {
    const stored = await getStoredPrimaryColor();
    const option = findPrimaryColorOption(stored);
    const id = option?.id ?? DEFAULT_PRIMARY_COLOR_ID;
    await PickerTheme.applyAccentStyle(`PickerAccent_${id}`);
  } catch {
    // best-effort only
  }
};
