#!/usr/bin/env node
/**
 * Generates Android color + style resources — one per entry in
 * src/theme/personalizationPalette.ts — so a native module can apply the
 * user's currently active accent color to the host Activity's theme before
 * opening a native picker (Android themes only resolve compiled resources,
 * never an arbitrary runtime RGB value).
 *
 * Source of truth: src/theme/personalizationPalette.ts. Regenerate whenever
 * that file's palette changes:
 *   node scripts/generateAndroidThemeColors.js
 *
 * Output (overwritten each run, do not edit by hand):
 *   android/app/src/main/res/values/theme_colors_generated.xml
 *   android/app/src/main/res/values/theme_styles_generated.xml
 */

const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.resolve(__dirname, '..');
const PALETTE_PATH = path.join(REPO_ROOT, 'src/theme/personalizationPalette.ts');
const COLORS_OUT = path.join(REPO_ROOT, 'android/app/src/main/res/values/theme_colors_generated.xml');
const STYLES_OUT = path.join(REPO_ROOT, 'android/app/src/main/res/values/theme_styles_generated.xml');

function parsePalette(source) {
  const defaultIdMatch = source.match(/DEFAULT_PRIMARY_COLOR_ID\s*=\s*'([^']+)'/);
  if (!defaultIdMatch) {
    throw new Error('Could not find DEFAULT_PRIMARY_COLOR_ID in personalizationPalette.ts');
  }
  const defaultId = defaultIdMatch[1];

  const entryRegex = /\{id:\s*(?:'([^']+)'|DEFAULT_PRIMARY_COLOR_ID)\s*,\s*name:\s*'[^']*'\s*,\s*hex:\s*'(#[0-9a-fA-F]{6})'\s*\}/g;
  const entries = [];
  let match;
  while ((match = entryRegex.exec(source)) !== null) {
    const id = match[1] ?? defaultId;
    const hex = match[2];
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(id)) {
      throw new Error(`Palette id "${id}" isn't a valid Android resource name — fix personalizationPalette.ts or this generator.`);
    }
    entries.push({id, hex});
  }
  if (entries.length === 0) {
    throw new Error('No palette entries matched — has the object shape in personalizationPalette.ts changed?');
  }
  return entries;
}

function buildColorsXml(entries) {
  const lines = entries.map(e => `    <color name="picker_accent_${e.id}">${e.hex}</color>`);
  return [
    '<?xml version="1.0" encoding="utf-8"?>',
    '<!-- GENERATED by scripts/generateAndroidThemeColors.js — do not edit by hand.',
    '     Regenerate: node scripts/generateAndroidThemeColors.js',
    '     Source of truth: src/theme/personalizationPalette.ts -->',
    '<resources>',
    ...lines,
    '</resources>',
    '',
  ].join('\n');
}

function buildStylesXml(entries) {
  const blocks = entries.map(e =>
    [
      `    <style name="PickerAccent_${e.id}" parent="AppTheme">`,
      `        <item name="colorAccent">@color/picker_accent_${e.id}</item>`,
      '    </style>',
    ].join('\n'),
  );
  return [
    '<?xml version="1.0" encoding="utf-8"?>',
    '<!-- GENERATED by scripts/generateAndroidThemeColors.js — do not edit by hand.',
    '     Regenerate: node scripts/generateAndroidThemeColors.js',
    '     Source of truth: src/theme/personalizationPalette.ts -->',
    '<resources>',
    ...blocks,
    '</resources>',
    '',
  ].join('\n');
}

function main() {
  const source = fs.readFileSync(PALETTE_PATH, 'utf8');
  const entries = parsePalette(source);
  fs.writeFileSync(COLORS_OUT, buildColorsXml(entries), 'utf8');
  fs.writeFileSync(STYLES_OUT, buildStylesXml(entries), 'utf8');
  console.log(`Generated ${entries.length} picker accent styles from ${path.relative(REPO_ROOT, PALETTE_PATH)}`);
  console.log(`  ${path.relative(REPO_ROOT, COLORS_OUT)}`);
  console.log(`  ${path.relative(REPO_ROOT, STYLES_OUT)}`);
}

main();
